### PR TITLE
Create topics with REST API

### PR DESCRIPTION
**Pull request by jasonbekolay**

### CODE REVIEW

**Comment by nchase** [comment]
can you add some tests that exercise this endpoints a bit?

**Comment by jasonbekolay** [comment]
Sure, I'll work on that next

**Comment by nchase** [comment]
@jasonbekolay: want me to deploy this as-is? just let me know

**Comment by jasonbekolay** [comment]
Not necessary.  Replying to topics is 95% of what I need, this can wait until there are tests to go with.

**Comment by animalextract1982** [comment]
we produce best Quality Novelty documents IDs and Passports, and Drivers license etc buy now high quality-We have the best
HOLOGRAMS AND DUPLICATING MACHINES With over 13million of out documents
circulating over the world.
-IDs Scan-yes...
-HOLOGRAMS: IDENTICAL
-BAR CODES: IDS SCAN
-UV: YES
FAKE and Real IDS WITH FAST SHIPPING - EMAIL SUPPORT



WhatsApp::::+237690914969
SKYPE: .....................( douglaswilliam411)
Tel/ ..............+237 690914969
Contact e-mails: (milleralexander366@gmail.com ).

**Pull request closed without merging**
