### PR TITLE
Rest api

### LINKED ISSUE #107: Unable to post with virus scanner installed on PC
I think I understand why I can't post on my work PC.  It has VIPRE antivirus running, and I think that's blocking any outgoing socket.emit calls.  I was able to sign up for the forum on that PC, but that uses a plain post.  I think incoming stuff from the socket works fine, but I'll pay closer attention this week.

Any thoughts on replacing socket call with an ajax call for posting?

### PR DESCRIPTION
**Pull request by jasonbekolay**
My first pass at a REST API, and changing the reply mechanism to post with ajax rather than the websocket.  I think posting with ajax will partially resolve #107, but I can't tell for sure until it's deployed.  (I can't run the application on the affected machine to test, and I haven't set up my own Heroku instance yet.)  If this is deployed, I'll test and report the results.

### CODE REVIEW

**Comment by jasonbekolay** [comment]
Forgot to mention - it doesn't completely resolve #107 because it doesn't deal with creating topics.  But if this solves the issues for posts, then it should be pretty easy to implement for topics.

**Comment by nchase** [comment]
awesome! I'll check this out in a bit.

**Comment by nchase** [comment]
so long as it checks that the user is authenticated (and it looks like it does) before making an API request I think we're good here.

I'm gonna deploy this, we'll try it out for a bit (~1-2 hours) on the forum and if nothing goes wrong I'll merge this PR into master. :thumbsup:

**Comment by nchase** [comment]
just saw your comment about you testing it. looks good to me so far, but by all means go ahead.

**Comment by nchase** [comment]
also: are you going to want to move [edit](https://github.com/twinlabs/forum/blob/restApi/app/views/posts/new.jade#L99-L106) and [delete](https://github.com/twinlabs/forum/blob/restApi/app/views/posts/new.jade#L68-L74) requests to talk to the HTTP API instead of through the socket?

**Comment by jasonbekolay** [comment]
Will test later tonight

**Comment by jasonbekolay** [comment]
It works as expected, so you can merge it whenever you want.  So on my work PC, anything incoming on the websocket works fine - new posts show immediately.  Outgoing stuff does not work at all.

I will implement edit, delete, and create topic with the API.  Leave #107 open until I do all that stuff.

I can now post at work now :+1:

**Comment by nchase** [comment]
:thumbsup: :thumbsup:

**Pull request merged**
