### PR TITLE
use node 4.x.x

### PR DESCRIPTION
**Pull request by nchase**
this commit upgrades us to node 4.x.x and lays a bit of groundwork for some other improvements.

### CODE REVIEW

**Comment by jasonbekolay** [comment]
Cool

**Comment by nchase** [comment]
@jasonbekolay hopefully this evening I'll have time to work out the test failures

**Comment by nchase** [comment]
looks like we suddenly think the test environment's token is wrong. will dig deeper later

**Comment by nchase** [comment]
not sure why the token I generate would change between node versions. that concerns me.

**Comment by nchase** [comment]
created #180 to address the weirdness between tokens and node versions – token generation still seems to work rather reliably, so this is good enough for now. deploying in a bit.

**Pull request merged**
